### ISSUE TITLE
Crosswalking IMOS records into OTN format

### ISSUE THREAD

**Issue by naomitress** [ocean-tracking-network/remora#1]
reviewing and giving feedback about example data shared to OTN (https://gitlab.oceantrack.org/otndc/otn-data-acquisition/-/issues/2591#note_102598)

@diniangela

**Comment by naomitress** [comment]
# Questions from OTN to IMOS

## general q's
- are times in local or UTC?

## missing fields
- `animal id`
- `wild_ind`
- `stock`

- `locality`


## missing tables
- project metadata

**Comment by diniangela** [comment]
Our project metadata uses the following tables and fields:

- projects
    - collectioncode (project code)
    - collaborationtype (Tracker, Deployment, or Data)
    - shortname
    - longname
    - citation
    - abstract
    - institutioncode
    - ocean
    - country
    - state
    - local_area
    - west_boundary, east_boundary (or could be a longitude centroid)
    - south_boundary, north_boundary (or could be a latitude centroid)
    - status (proposed, in progress, or complete)
    - start date and end date
    - website
- contacts
    - collectioncode (project code)
    - firstname
    - lastname
    - email
    - phone number
    - address
    - affiliation (or institution they belong to)
    - website
    - orcid (if given)
    - role (role in project)
    - is_point_of_contact (shows if they are the point of contact or not)
- species
    - collectioncode (project code)
    - scientific name
    - common name
    - aphiaid (from WoRMS)

**Comment by naomitress** [comment]
@diniangela is there no equivalent for rcvr_locations from the IMOS export?

**Comment by fjaine** [comment]
> # Questions from OTN to IMOS
> ## general q's
> 
>     * are times in local or UTC?

YES times are in UTC
> 
> ## missing fields
> ### animals and transmitters
> 
>     * `animal id`
> 
>     * `wild_ind`
> 
>     * `stock`
> 
>     * `collector`
 
These are not available.

> ### receivers
> 
>     * `locality`

This is not relevant as GPS coordinates are provided.

> ## missing tables
> 
>     * project metadata

This is not available at this stage other than the project name.

**Comment by fjaine** [comment]
'collector' should be IMOS Animal Tracking Facility

**Comment by fjaine** [comment]
Not sure about the below:

>datereleaseanimal | IMOS_transmitter_deployment_metadata.embargo_date
>-- | --
>datedetectionsreleased | imos_detections.embargo_date

Embargoes are assigned to transmitters in our system, not detections. As such, any detection associated with a transmitter will not become public until the transmitter's embargo lapses.

**Comment by fjaine** [comment]
coordinateprecision : WGS 84

**Comment by diniangela** [comment]
Ok great, fixed some of the fields in the mapping

The 'wild_ind' would be the wild indicator (wild or hatchery) so I'll put 'wild'

Stock is the `body of water of origin for animal or rive of origin for fish`, it's ok to be 'unknown' so I can use that

The 'collector' would be the person doing the tagging or deploying of the receiver but yup I can put 'IMOS Animal Tracking Facility'

**Comment by jdpye** [comment]
For embargo being attached to detections, we also track embargo dates by transmitter but we attach a 'releasedate' column to each detection that is calculated using the embargo period/date for that transmitter. Calculable on our side if we've got the date alongside the transmitters.

**Comment by jdpye** [comment]
Stock comes from the freshwater folks who were co-designing this template at OTN's inception, they had some specifics they wanted to make note of and it's part of the official template now and is often left blank or 'unknown' for any ocean-going species.

**Comment by fjaine** [comment]
> Stock comes from the freshwater folks who were co-designing this template at OTN's inception, they had some specifics they wanted to make note of and it's part of the official template now and is often left blank or 'unknown' for any ocean-going species.

Sounds like one of those less essential fields :)

You could always say 'Australia' if you want to capture the origin of the stock/population being tagged.

**Comment by naomitress** [comment]
> > Stock comes from the freshwater folks who were co-designing this template at OTN's inception, they had some specifics they wanted to make note of and it's part of the official template now and is often left blank or 'unknown' for any ocean-going species.
> 
> You could always say 'Australia' if you want to capture the origin of the stock/population being tagged. For ocean-going species, the country of origin might allow OTN to track connectivity between the various networks/countries involved in the global network :)

The problem i see with saying 'Australia' is thats making an assumption on the origin of the animal, `Stock` would be the nursery, hatching river, or even an indication of the results of genetic analysis, not just where the animal is captured/released after tagging (we grab those with other fields)

**Comment by naomitress** [comment]
looking at populating a bit more of the project metadata, we can maybe join to other sources later down the line, is the project name the right identifier for getting records off of the IMOS website? or is there a `project id` that would serve us better?

**Comment by naomitress** [comment]
@fjaine i'm revisiting the project metadata issue, specifically for the tag records youre passing.  We think we will be ok without any additional project contact info for the receiver projects for now, but for the tags, do you have **contact info** that can be shared for the researchers releasing the tags? specifically

- first last name
- email
- organization
- project role 

even if there is just one contact per project we can make that work, including extending the organization to represent the project as well as the individual.  If it occurs that tags passed this way are detected on receivers in our system, we want to be able to share those detections to the researchers

second question, the project background, the value **tagging_project_name** is there, do you have any of the following available

- project abstract
- citation

we think we can work with the locations of the tag releases to help bound the project geographically, and are willing to use the first tag release date, and last detection, to bound the project temporally

lastly do you have the information you referred to for tag embargo end dates? are all tag records being shared this way by default out of embargo? (if so we can use the date loaded as embargo end date)

**Comment by jackVanish** [comment]
This is being handled in Surimi now so I'm closing this ticket here.
