### ISSUE TITLE
Mapping for IMOS metadata to become OTN metadata

### ISSUE THREAD

**Issue by jackVanish** [ocean-tracking-network/remora#10]
[otn_imos_column_map.txt](https://github.com/ocean-tracking-network/remora/files/10013264/otn_imos_column_map.txt)

**Is your feature request related to a problem? Please describe.**
We've already built in a function for taking OTN-format metadata (detection extract, tag, and receiver metadata) and rearranging it into IMOS-formatted data (approximately). There's now interest in going the other way- IMOS to OTN. The function attached is how we do it for OTN to IMOS, we need a mapping of columns from IMOS to OTN so we can do the reverse. 

**Describe the solution you'd like**
We'll ultimately produce three files: detections, tags, and receivers. For each column in each OTN file, we'll need the following:
1. the equivalent column in the IMOS metadata, OR, the columns that will be merged to produce the relevant data. 
2. the fallback column to use. In the same way that we can "derive" tag and receiver metadata in the OTN -> IMOS process, we should be able to do the same in the opposite direction. So if we don't have Receiver or Tag metadata, what columns should we use to produce that data?
3. If neither of the above two are applicable, then indicate that the column should be populated with NA values. 

**Describe alternatives you've considered**
I have thought about comparing the files myself and going from there, and will start from that to get underway, but ultimately I want to defer to people who are closer to the data and will know its use and meaning more completely than I will. 

**Additional context**
There is an existing ticket here: https://github.com/ocean-tracking-network/remora/issues/1 which covers database column mappings, which I expect will be a useful guide in answering some of the initial questions. Although it's not metadata-to-metadata, since our metadata maps into our database columns we may be able to use this to get a sense of where we want to go.

**Comment by naomitress** [comment]
roughly:
imos animal measure + imos transmitter deployment == otn tag metadata
imos detections == otn detection extract
imos receiver deployment metadata == otn receiver metadata

**Comment by CaitlinBate** [comment]
[IMOS metadata mapping.xlsx](https://github.com/ocean-tracking-network/remora/files/10025082/IMOS.metadata.mapping.xlsx)

**Comment by jackVanish** [comment]
This functionality is now going to be handled in surimi, so I'm closing these tickets.
